# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xa7z010clg400-1Q

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/mizo4/vga_controller/vga_controller.cache/wt [current_project]
set_property parent.project_path C:/Users/mizo4/vga_controller/vga_controller.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/mizo4/vga_controller/vga_controller.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/mizo4/UART/UART.srcs/sources_1/new/UART.v
  C:/Users/mizo4/vga_controller/vga_controller.srcs/sources_1/new/ascii_rom.v
  C:/Users/mizo4/UART/UART.srcs/sources_1/new/baud.v
  C:/Users/mizo4/vga_controller/vga_controller.srcs/sources_1/new/cursor_move.v
  C:/Users/mizo4/vga_controller/vga_controller.srcs/sources_1/new/fifo.v
  C:/Users/mizo4/vga_controller/vga_controller.srcs/sources_1/new/fifo_control.v
  C:/Users/mizo4/fifo_buffer/fifo_buffer.srcs/sources_1/new/reg_memory_file.v
  C:/Users/mizo4/UART/UART.srcs/sources_1/new/rx.v
  C:/Users/mizo4/vga_controller/vga_controller.srcs/sources_1/new/text_gen.v
  C:/Users/mizo4/vga_controller/vga_controller.srcs/sources_1/new/vga_sync.v
  C:/Users/mizo4/vga_controller/vga_controller.srcs/sources_1/new/vga_controller.v
  C:/Users/mizo4/vga_controller/vga_controller.srcs/sources_1/new/debounce.v
  C:/Users/mizo4/vga_controller/vga_controller.srcs/sources_1/new/top_vga.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/mizo4/vga_controller/vga_controller.srcs/constrs_2/new/const.xdc
set_property used_in_implementation false [get_files C:/Users/mizo4/vga_controller/vga_controller.srcs/constrs_2/new/const.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top_vga -part xa7z010clg400-1Q


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_vga.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_vga_utilization_synth.rpt -pb top_vga_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
